### ISSUE TITLE
Unable to locate program input point inflatevalidate in DLL.

### ISSUE THREAD

**Issue by Zhaoyazhou1996** [libvips/build-win64-mxe#27]
Hi,
I am trying to test the [32-bit binary of libvips](https://github.com/libvips/build-win64-mxe/releases/download/v8.10.6/vips-dev-w32-all-8.10.6.zip), But when I run a simple test program, I encounter a problem as shown in the figure：
![error](https://user-images.githubusercontent.com/49519766/121157600-4a1f5780-c87c-11eb-9f29-876fede0b7ee.png)
The code I tested is as follows：
```c
#include <stdio.h>
#include <vips/vips.h>
#include <Windows.h> 

int main(void)
{
    char* filePath = "D:\\test\\30203b.tif";
    VipsImage* image;

    if (VIPS_INIT(filePath))
        vips_error_exit(NULL);

    if (!(image = vips_image_new_from_file(filePath, NULL)))
        vips_error_exit(NULL);
    g_object_unref(image);
    getchar();
    return(0);
}

```
Is this a known issue? Am I doing something wrong?
Best regards!

**Comment by kleisauke** [comment]
The `inflateValidate` symbol originates from zlib (`libz.dll`), so perhaps there's a conflicting DLL file in your PATH environment variable? There are a few things you could try:
- Try to reorder your PATH environment variable so that the `vips` bin directory (for e.g. `C:\vips-dev-8.10\bin`) is included first.
- Try to test with `vips.exe` outside the `bin` directory, for example:
   ```bash
   vips copy x.jpg x.png
   ````
   If it'll throw any error, the wrong DLLs are being loaded.
- Use the [`Dependencies`](https://lucasg.github.io/Dependencies/) program to check if all dependencies can be found and if they are picked up from the correct location.
- Use the statically-linked "web" variant (`vips-dev-w32-web-8.10.6-static.zip`) to avoid potential collisions.

**Comment by Zhaoyazhou1996** [comment]
Thank you for your excellent comment! I reorder my PATH environment and search `libz.dll` in `C:` and `D` disk, and deleted the redundant `libz.dll`. My program can run normally now. Thank you again!
